Fixed cache

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,10 +26,8 @@ jobs:
         with:
           path: ~/.cargo/bin/cargo2junit
           key: ${{ runner.os }}-cargo2junit
-      - uses: actions-rs/cargo@v1
-        with:
-          command: install
-          args: cargo2junit
+      - name: install cargo2junit
+        run: cargo install cargo2junit || true # ignore failure, since it means that it's already in cache
       - name: Test
         run: cargo test --all-features --no-fail-fast -- -Z unstable-options --format json --report-time | tee results.json && cat results.json | cargo2junit > results.xml
         env:
